config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  get 'signup', to: 'users#new'

  resources :users, only: [:index, :show, :create, :edit, :update, :destroy]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :rooms
  
  post 'reservations/confirm'
  post 'reservations/back'
  post 'reservations/complete'
  resources :reservations
  
  get 'search' => 'rooms#search', as: 'search'
  get 'search' => 'rooms#search_area', as: 'search_area'

  get '/', to: 'users#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :person_num, presence: true

  belongs_to :room, optional: true
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true
  validates :room_introduce, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :room_image, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :person_num, presence: true

  mount_uploader :room_image, ImageUploader

  has_many :reservations, dependent: :destroy

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
 
  validates :nickname, presence: true, length: { maximum: 50 }
  validates :introduce, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }

  has_secure_password

  mount_uploader :image, ImageUploader

  has_many :rooms
  has_many :reservations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private
    
  def logged_in_user
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  def index
    @reservations = Reservation.all
  end

  def show
  end

  def new
    @reservation = Reservation.new
  end

  def edit
  end

  def create
    @reservation = Reservation.new(reservation_params)

    if @reservation.save
      redirect_to @reservation, notice: "Reservation was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def back
		@reservation = Reservation.new(session[:reservation])
		session.delete(:reservation)
		redirect_to "/rooms/#{params[:room_id]}"
	end

  def confirm
		@reservation = Reservation.new(reservation_params)
		session[:reservation] = @reservation
		if @reservation.invalid?
			render :new
		end
	end

  def complete
		Reservation.create!(session[:reservation])
		session.delete(:reservation)
	end

  private
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    def reservation_params
      params.require(:reservation).permit(:user_id, :room_id, :start_date, :end_date, :person_num)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    
    if @room.save
      flash[:success] = '新しいユーザーを登録しました。'
      redirect_to rooms_path
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  def search
    if params[:search_area].present?
      @rooms = Room.where("address like?", "%#{params[:search_area]}%")
      @keyword = params[:search_area]
      render "search"
    else
      @rooms = Room.where("name like?", "%#{params[:search]}%")
      @keyword = params[:search]
      render "search"
    end
  end

  private

  def room_params
    params.require(:room).permit(:user_id, :name, :room_introduce, :price, :address, :room_image)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to controller: :users, action: :index
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to controller: :users, action: :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only:[:edit, :update, :destroy]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = '新しいユーザーを登録しました。'
      redirect_to users_path
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if current_user == @user
      if @user.update(user_params)
        flash[:success] = 'ユーザー情報を編集しました。'
        render :edit
      else
        flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
        render :edit
      end   
    else
      redirect_to root_url
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :image, :introduce,)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>ArService</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header>
      <div class="d-flex bd-highlight align-items-center bgc-black">
        <div class="p-2 bd-highlight">
          <a href="/users">
            <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png" alt="サイトのロゴ画像">
          </a>
        </div>
        <div class="p-2 bd-highlight">
          <%= form_tag search_path, method: :get do %>
            <%= text_field_tag :search_area, params[:search_area], placeholder: "エリアを入力", class: "index-h" %>
          <% end %>
        </div>
        <div class="p-2 bd-highlight">
          <%= form_tag search_path, method: :get do %>
            <%= text_field_tag :search, params[:search], placeholder: "キーワードを入力", class: "index-h" %>
          <% end %>
        </div>
  
        <% if logged_in? %>
          <%= render 'users/logged_in' %>
        <% else %>
          <%= render 'users/not_logged_in' %>
        <% end %>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>© 2020 POTEPAN.INC.</p>
    </footer>
    
  </body>
</html>

app/views/reservations/complete.html.erb
<div class="device_frame confirm">
  <h1>予約フォーム</h1>
  <ol class="nav my-4">
    <li>1.確認</li>
    <li class="current">2.完了</li>
  </ol>
  <p class="confirm-date text-center mt-5">ご予約ありがとうございました。</p>
</div>

app/views/reservations/confirm.html.erb
<div class="device_frame confirm">
  <h1>予約フォーム</h1>
  <ol class="nav my-4">
    <li class="current">1.確認</li>
    <li>2.完了</li>
  </ol>
  <dl>
	<div class="mt-5 mb-3 confirm-date">
      <dt>開始日</dt>
      <dd><%= @reservation.start_date %></dd>
    </div>
	<div class="mb-3 confirm-date">
	  <dt>終了日</dt>
      <dd><%= @reservation.end_date %></dd>
    </div>
	<div class="mb-3 confirm-date">
	  <dt>人数</dt>
      <dd><%= @reservation.person_num %>人</dd>
    </div>
	<div class="mb-5 confirm-date">
	  <dt>合計金額</dt>
      <dd>¥<%= (@reservation.end_date - @reservation.start_date).to_i * @reservation.room.price.to_i * @reservation.person_num %></dd>
    </div>
  </dl>
  <div class="text-center">
    <%= link_to "入力画面に戻る", @reservation.room, class: 'btn btn-block confirm-btn confirm-width mb-3' %>
    <%= form_for @reservation, method: :post, url: reservations_complete_path do |form| %>
      <%= form.submit '送信する', class: 'btn btn-block confirm-btn confirm-width' %>
    <% end %>
  </div>
</div>

app/views/reservations/index.html.erb
<div class="container-fiuld reservation-posts row">
  <h4 class="pb-4">予約済みルーム一覧</h4>
  <table>
    <thead>
      <tr>
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
      </tr>
    </thead>
    <tbody>
      <% @reservations.each do |reservation| %>
        <% if reservation.user_id == current_user.id %>
          <tr>
            <td><%= link_to image_tag(reservation.room.room_image.url, :size => "240x140"), reservation.room %></td>
            <td class="posts-name"><%= link_to reservation.room.name, reservation.room %></td>
            <td class="posts-content"><%= reservation.room.room_introduce %></td>
            <td class="rindex-f">¥ <%= (reservation.end_date - reservation.start_date).to_i * reservation.room.price.to_i * reservation.person_num %></td>
            <td class="rindex-f"><%= reservation.start_date %></td>
            <td class="rindex-f"><%= reservation.end_date %></td>
            <td class="rindex-f"><%= reservation.created_at.strftime("%Y-%-m-%-d %-H:%M") %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reservations/new.html.erb
<div class="row container">
  <div class="col-md-8">
    <div>
      <% if @reservation.room.room_image? %>
        <%= image_tag @reservation.room.room_image.url, class: "room-show-profile-image" %>
      <% else %>
        <%= image_tag("/images/icon/icon-mama-02-160px.png") %>
      <% end %>
    </div>
    <div class="room-show-detile">
      <div>
        <%= image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg", :size => "65x65" , class: "room-show-detile-icon") %>
      </div>
      <div class="room-show-profile">
        <p class="room-show-profile-name"><%= @reservation.room.name %></p>
        <p class="room-show-profile-address"><%= @reservation.room.address %></p>
      </div>
    </div>
    <div class="room-show-profie-introduce">
      <%= @reservation.room.room_introduce %>
    </div>
  </div>
  <div class="col-md-4 border room-show-nav">
    <%= form_for @reservation, method: :post, url: reservations_confirm_path do |form| %>
      <div class="field mb-3">
        ¥ <%= @reservation.room.price %> / 日
      </div>
      <div  class="form-group mb-3">
        <%= form.label :start_date, '開始日' %>
        <%= form.date_field :start_date, class: 'form-control' %>
      </div>
      <div  class="form-group mb-3">
        <%= form.label :end_date, '終了日' %>
        <%= form.date_field :end_date, class: 'form-control' %>
      </div>
      <div  class="form-group mb-3">
        <%= form.label :person_num, '人数' %>
        <%= form.number_field :person_num, class: 'form-control' %>
      </div>
      <% if logged_in? %>
        <div class="actions">
          <%= form.submit '予約する', class: 'btn btn-primary btn-block my-3 form-control' %>
        </div>
      <% else %>
        <a href="/login" class='btn btn-primary btn-block my-3 form-control'>予約する</a>
      <% end %>

      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.hidden_field :room_id, value: @reservation.room.id %>
    <% end %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="container-fiuld room-posts row">
  <h4 class="pb-4">登録済みルーム一覧</h4>
  <table>
    <thead>
      <tr>
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>作成日</th>
      </tr>  
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
        <% if room.user_id == current_user.id %>
          <tr>
            <td><%= link_to image_tag(room.room_image.url, :size => "240x140"), room %></td>
            <td class="posts-name"><%= link_to room.name, room %></td>
            <td class="posts-content"><%= room.room_introduce %></td>
            <td class="rindex-f">¥ </a><%= room.price %></td>
            <td class="rindex-f"><%= room.created_at.strftime("%Y-%-m-%-d %-H:%M") %></td>
          </tr>
        <% end %>
      <% end %> 
    </tbody>
  </table>
</div>

app/views/rooms/new.html.erb
<div class="row p-4 device_frame border">
  <div>
    <h1 class="mb-3">ルーム情報登録</h1>
    <%= form_for(@room) do |f| %>
      <div class="form-group me-3 mb-3">
        <%= f.label :name, 'ルーム名' %>
        <%= f.text_field :name, placeholder: "ルーム名を入力", class: 'form-control' %>
      </div>
      <div class="form-group me-3 mb-3">
        <%= f.label :room_introduce, 'ルーム紹介' %>
        <%= f.text_area :room_introduce, :size => "80x5", placeholder: "ルーム説明を入力", class: 'form-control' %>
      </div>
      <div class="form-group me-3 mb-3">
        <%= f.label :price, '料金' %>
        <%= f.number_field :price, placeholder: "一日あたりの料金を入力", class: 'form-control' %>
      </div>
      <div class="form-group me-3 mb-3">
        <%= f.label :address, '住所' %>
        <%= f.text_field :address, placeholder: "住所を入力", class: 'form-control' %>
      </div>
      <div class="form-group me-3 mb-3">
        <%= f.label :room_image, 'ルーム画像' %><br>
        <%= f.file_field :room_image %>
      </div>
      <div class="al-c">
        <%= f.submit '登録', class: 'btn btn-primary btn-block my-3 form-control' %>
      </div>

      <%= f.hidden_field :user_id, value: current_user.id %>
    <% end %>
  </div>
</div>

app/views/rooms/search.html.erb
<div class="container">
  <h4 class="pb-4">検索結果：<%= @rooms.count %>件</h4>
  <div class="row">
    <% @rooms.each do |room| %>
      <div class="col-sm-6 col-lg-4 col-xl-3 mb-4 search-result">
        <div class="border">
          <%= link_to(room, class: "text-decoration-none") do %>
            <div><%= image_tag room.room_image.url, class: "room-image" %></div>
            <div class="room-profile">
              <p class="room-profile-name"><%= room.name %></p>
              <p class="room-profile-city"><%= room.address %></p>
              <p class="room-profile-icon">¥<%= room.price %></p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %> 
  </div> 
</div>

app/views/rooms/show.html.erb
<div class="row container">
  <div class="col-md-8">
    <div>
      <% if @room.room_image? %>
        <%= image_tag @room.room_image.url, class: "room-show-profile-image" %>
      <% else %>
        <%= image_tag("/images/icon/icon-mama-02-160px.png") %>
      <% end %>
    </div>
    <div class="room-show-detile">
      <div>
        <%= image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg", :size => "65x65" , class: "room-show-detile-icon") %>
      </div>
      <div class="room-show-profile">
        <p class="room-show-profile-name"><%= @room.name %></p>
        <p class="room-show-profile-address"><%= @room.address %></p>
      </div>
    </div>
    <div class="room-show-profie-introduce">
      <%= @room.room_introduce %>
    </div>
  </div>
  <div class="col-md-4 border room-show-nav">
    <%= form_for @reservation, method: :post, url: reservations_confirm_path do |form| %>
      <div class="field mb-3">
        ¥ <%= @room.price %> / 日
      </div>
      <div  class="form-group mb-3">
        <%= form.label :start_date, '開始日' %>
        <%= form.date_field :start_date, class: 'form-control' %>
      </div>
      <div  class="form-group mb-3">
        <%= form.label :end_date, '終了日' %>
        <%= form.date_field :end_date, class: 'form-control' %>
      </div>
      <div  class="form-group mb-3">
        <%= form.label :person_num, '人数' %>
        <%= form.number_field :person_num, class: 'form-control' %>
      </div>
      <% if logged_in? %>
        <div class="actions">
          <%= form.submit '予約する', class: 'btn btn-primary btn-block my-3 form-control' %>
        </div>
      <% else %>
        <a href="/login" class='btn btn-primary btn-block my-3 form-control'>予約する</a>
      <% end %>

      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.hidden_field :room_id, value: @room.id %>
    <% end %>
  </div>
</div>

app/views/users/_logged_in.html.erb
<div class="ms-auto p-2 bd-highlight d-flex align-items-center">
  <%= current_user.nickname %>
  <div class="dropdownmp">
    <button class="dropdown__btn" id="dropdown__btn">
      <% if current_user.image? %>
        <%= image_tag current_user.image.url, :size => "65x65", class: "host-icon" %>
      <% else %>
        <%= image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg", :size => "65x65", class: "host-icon") %>
      <% end %>
    </button>
    <div class="dropdown__body">
      <ul class="dropdown__list">
        <li class="dropdown__item"><%= link_to 'ルーム登録', new_room_path, class: "dropdown__item-link" %></li>
        <li class="dropdown__item"><%= link_to '予約済みルーム一覧', reservations_path, class: "dropdown__item-link" %></li>
        <li class="dropdown__item"><%= link_to '登録済みルーム一覧', rooms_path, class: "dropdown__item-link" %></li>
        <li class="dropdown__item"><%= link_to '設定', edit_user_path(current_user), class: "dropdown__item-link" %></li>
        <li class="dropdown__item"><%= link_to "ログアウト", logout_path, method: :delete, class: "dropdown__item-link" %></li>
      </ul>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'user/logged_in' %>

app/views/users/_not_logged_in.html.erb
<div class="ms-auto p-2 bd-highlight d-flex align-items-center">
  <button type="button" class="btn btn-primary my-2">
    <%= link_to "ログイン", login_path, class: "c-white" %>
  </button>
  <button type="button" class="btn btn-secondary my-2 mx-3">
    <%= link_to '登録する', signup_path, class: "c-white" %>
  </button>
</div>

app/views/users/edit.html.erb
<div class="row p-4">
  <aside class="col-md-4 edit-mt">
    <div class="panel panel-default border border-2 edit-br">
      <div class="panel-heading edit-b p-1 cccccc">
        <h3 class="panel-title text-center"><%= @user.nickname %></h3>
      </div>
      <div class="m-3">
        <div class="panel-body al-c">
          <% if current_user.image? %>
            <%= image_tag current_user.image.url, :size => "110x110", class: "d-block mx-auto" %>
          <% else %>
            <%= image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg", :size => "110x110", class: "d-block mx-auto") %>
          <% end %>
        </div>
        <%= form_for(@user) do |f| %>
          <div class="form-group mt-2">
            <%= f.file_field :image, class: "edit-w" %>
          </div>
        <% end %>
      </div>
    </div>
  </aside>

  <div class="col-md-8">
    <h1 class="mb-3">プロフィール編集画面</h1>
    <%= form_for(@user) do |f| %>
      <div class="form-group me-3 mb-3">
        <%= f.label :nickname, '名前' %><br>
        <%= f.text_field :nickname, class: 'form-control' %>
      </div>
      <div class="form-group me-3 mb-3">
        <%= f.label :email, 'メールアドレス' %><br>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group me-3 mb-3">
        <%= f.label :introduce, '自己紹介（255文字未満）' %>
        <%= f.text_area :introduce, :maxlength => "255", :size => "80x5", class: 'form-control' %>
      </div>
      <div class="accbox">
        <div class="accshow">
          <div class="form-group me-3 mb-3">
            新しいパスワード（変更する場合のみ入力）<br>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group me-3 mb-3">
            新しいパスワードを再入力（変更する場合のみ入力）<br>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="al-c">
        <%= f.submit '変更する', class: 'btn btn-primary mt-3' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="wrap">
  <div class="bgi">
    <div class="form-fream">
      <div class="bgc-white">
        <p class="form-area-title mb-4">Potepan Shareでまだ体験したことのない旅をしよう</p>
        <%= form_tag search_path, method: :get do %>
          <div class="index-mb"><%= label_tag 'エリア'%></div>
          <div><%= text_field_tag :search_area, params[:search_area], placeholder: "東京", class: "form-control mb-4" %></div>
          <div><%= submit_tag '探す', class: "form-control btn-primary mb-4" %></div>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="m-5">
    <h1 class="section-title">おすすめのエリア</h1>
    <div class="index-f">
      <div class="panel-item">
        <a href="/search?search_area=東京">
          <img class="panel-image" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg">
          <div class="area">東京</div>
        </a>
      </div>
      <div class="panel-item">
        <a href="/search?search_area=大阪">
          <img class="panel-image" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_osaka.jpg">
          <div class="area">大阪</div>
        </a>
      </div>
      <div class="panel-item">
        <a href="/search?search_area=京都">
          <img class="panel-image" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_kyoto.jpg">
          <div class="area">京都</div>
        </a>
      </div>
      <div class="panel-item">
        <a href="/search?search_area=札幌">
          <img class="panel-image" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_sapporo.jpg">
          <div class="area">札幌</div>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="device_frame border">
  <h1 class="mb-3">新しいアカウントを作成</h1>
  <%= form_for(@user) do |f| %>
    <div class="form-group mb-3">
      <%= f.label :nickname, 'ニックネーム' %>
      <%= f.text_field :nickname, class: 'form-control' %>
    </div>
    <div class="form-group mb-3">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group mb-3">
      <%= f.label :password, 'パスワード' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group mb-3">
      <%= f.label :password_confirmation, 'パスワード（もう１度ご入力ください）' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class="unew-ta-center">
      <%= f.submit '登録する', class: 'btn btn-primary btn-block my-3 form-control' %>
    </div>
  <% end %>
  <div class="text-center">
    <a href="/login">すでにアカウントをお持ちの方はログイン</a>
  </div>
</div>